### ISSUE TITLE
CARSON: when change colour scheme it works, but no popup/action that tells me it worked 

### ISSUE THREAD

**Issue by michaelalbinson** [essdev-team/dibs-wrapper#33]
(other than going to a page to see it)

Should probably either force-reload the page (but it needs to go back to the preferences pane) or show a pop-up telling the user that the change was successful.

**Comment by ruffoa** [comment]
Hows this:
![theming-fix](https://user-images.githubusercontent.com/9133965/42398594-550f35ac-8162-11e8-9b19-b665011b8f88.gif)

Good enough? 😸

**Comment by michaelalbinson** [comment]
Oooh very pretty

**Comment by ruffoa** [comment]
Now, should it change only on the save button being hit, or whenever you change the selected theme in the dropdown?  It uses JS to change the style, so this might not be super fast on slower devices (**cough** old phones **cough**)
