### ISSUE TITLE
QuickBook™ Should probably redirect you off the QuickBook™ page

### ISSUE THREAD

**Issue by michaelalbinson** [essdev-team/dibs-wrapper#35]
Seeing as there's really nothing to do on the QuickBook™ page except click QuickBook™

**Comment by ruffoa** [comment]
Not sure how we should handle this, given the new feature of QuickBook™ that will book a room for the proceeding hour if you click it again

**Comment by ruffoa** [comment]
say I have 2 upcoming meetings, one after another, at the moment all I have to do is click the QuickBook™ button twice, and I'll get two separate bookings for the next two hours

**Comment by ruffoa** [comment]
With the new QuickBook™ page, you can click the button as many times as you want, and it'll give you a booking for the chosen time, so it makes sense to leave them on the page now
